#!/bin/bash
if [ -f /var/run/reboot-required ];
then
status=1
statustxt="- WARN: System Restart Required"
else
status=0
statustxt="- OK: No System Restart Required"
fi
echo "$status restart_required $statustxt"
